sudo: required

language: ruby

env:
  global:
  - JEKYLL_BUILD="/opt/jekyll/scripts/jekyllBuild.sh"
  - DEPLOY="/opt/jekyll/scripts/deploy.sh"
  - VOLUME="/opt/jekyll"
  - BUILD_FILE="$/opt/jekyll/builds/ugly.zip"
  - JS_FOLDER="$/opt/jekyll/builds/pretty/assets/js"
  - CSS_FOLDER="$/opt/jekyll/builds/pretty/css"

banches:
  only:
  - master
services:
  - docker
before_install: 
install:

before_script:
  - docker pull starefossen/ruby-node
script:
  - > 
    docker run --label=jekyll -v $(pwd):$VOLUME -it 
    -p 127.0.0.1:4000:4000 
    -e VOLUME=$VOLUME 
    -e PRETTY_BUILD_FOLDER=$PRETTY_BUILD_FOLDER 
    -e BUILD_FILE=$BUILD_FILE 
    -e JS_FOLDER=$JS_FOLDER 
    -e CSS_FOLDER=$CSS_FOLDER 
    -e test=$test
    starefossen/ruby-node /bin/sh $JEKYLL_BUILD

after_script: 

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master


after_deploy: 
